mode = "edge"

[commander]
edges = ["127.0.0.1:50051"]

[edge]
commander_address = "127.0.0.1:50051"

[load]
rps = 10
duration_seconds = 10
concurrency = 2
payload = "GET / HTTP/1.1\r\nHost: example\r\n\r\n"
arrow_output = "kukai_metrics.arrow"
reuse_connection = true

[[load.targets]]
addr = "127.0.0.1"
port = 8080
weight = 1.0
